"""
Function definitions for various potential flows
"""
import numpy as np
from matplotlib import pyplot as plt

def source(xs, ys, Sstr, X, Y):
    """
    Returns the velocity and stream function field generated by the source(s)
    
    Parameters
    ----------
    xs: Numpy column vector
         x-coordinate of the source
    ys: Numpy column vector
         y-coordinate of the source
    Sstr: Numpy column vector
           strength of the source
    X, Y: 2D np arrays
          grid generated by np.meshgrid( )         
    
    Returns
    -------
    u: 2D Numpy array of floats
       x-component of the velocity field
    v: 2D Numpy array of floats
       y-component of the velocity field
    psi: 2D np array of floats
       stream function field
    
    """
    
    # initialize u, v and psi
    u = np.zeros(np.shape(X))
    v = np.zeros(np.shape(X))
    psi = np.zeros(np.shape(X))     
    
    for i in range(0, np.shape(xs)[0]):
        
        # radial distance and angle from source
        r   = np.sqrt( (X - xs[i])**2 + (Y - ys[i])**2)
        theta = np.arctan2(Y - ys[i], X - xs[i])
        
        # velocity field
        u = u + 0.5 * Sstr[i] / (np.pi * r) * np.cos(theta) 
        v = v + 0.5 * Sstr[i] / (np.pi * r) * np.sin(theta)
    
        #stream function
        psi = psi + 0.5 * Sstr[i] / np.pi * np.arctan2((Y - ys[i]), (X - xs[i])) 
    
    return u, v, psi 

